---
- name: Install k3s on control plane
  hosts: controlplane
  become: yes
  roles:
    - role: k3s
      vars:
        k3s_role: server

- name: Install k3s on worker nodes
  hosts: workers
  become: yes
  roles:
    - role: k3s
      vars:
        k3s_role: agent
