---
- name: Download k3s install script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s_install.sh
    mode: '0755'

- name: Install k3s server
  shell: INSTALL_K3S_EXEC="--disable traefik" sh /tmp/k3s_install.sh
  args:
    creates: /usr/local/bin/k3s
  when: k3s_role == 'server'

- name: Get join token
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: token_file
  delegate_to: "{{ groups['controlplane'][0] }}"
  run_once: true
  when: k3s_role == 'agent'

- name: Set token fact
  set_fact:
    server_token: "{{ token_file.content | b64decode }}"
  when: k3s_role == 'agent'

- name: Install k3s agent
  shell: |
    K3S_URL=https://{{ hostvars[groups['controlplane'][0]].ansible_host | default(groups['controlplane'][0]) }}:6443 \
    K3S_TOKEN={{ server_token }} sh /tmp/k3s_install.sh
  args:
    creates: /usr/local/bin/k3s
  when: k3s_role == 'agent'

- name: Download kubeconfig
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ./kubeconfig
    flat: yes
  when: k3s_role == 'server'
