---
- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes

- name: Add Helm GPG key
  shell: |
    curl https://baltocdn.com/helm/signing.asc | gpg --dearmor > /usr/share/keyrings/helm.gpg
  args:
    creates: /usr/share/keyrings/helm.gpg

- name: Add Helm apt repository
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" > /etc/apt/sources.list.d/helm-stable-debian.list
  args:
    creates: /etc/apt/sources.list.d/helm-stable-debian.list

- name: Update apt cache for Helm repository
  apt:
    update_cache: yes

- name: Install Helm
  apt:
    name: helm
    state: present

- name: Install cert-manager
  kubernetes.core.helm:
    name: cert-manager
    chart_repo_url: https://charts.jetstack.io
    chart_ref: cert-manager
    release_namespace: cert-manager
    create_namespace: true
    release_values:
      installCRDs: true
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Install Longhorn
  kubernetes.core.helm:
    name: longhorn
    chart_repo_url: https://charts.longhorn.io
    chart_ref: longhorn
    release_namespace: longhorn-system
    create_namespace: true
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Install NGINX Ingress Controller
  kubernetes.core.helm:
    name: ingress-nginx
    chart_repo_url: https://kubernetes.github.io/ingress-nginx
    chart_ref: ingress-nginx
    release_namespace: ingress-nginx
    create_namespace: true
    kubeconfig: /etc/rancher/k3s/k3s.yaml
