---
- name: Install Helm
  apt:
    name: helm
    state: present
    update_cache: yes

- name: Install cert-manager
  kubernetes.core.helm:
    name: cert-manager
    chart_repo_url: https://charts.jetstack.io
    chart_ref: cert-manager
    release_namespace: cert-manager
    create_namespace: true
    release_values:
      installCRDs: true
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Install Longhorn
  kubernetes.core.helm:
    name: longhorn
    chart_repo_url: https://charts.longhorn.io
    chart_ref: longhorn
    release_namespace: longhorn-system
    create_namespace: true
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Install NGINX Ingress Controller
  kubernetes.core.helm:
    name: ingress-nginx
    chart_repo_url: https://kubernetes.github.io/ingress-nginx
    chart_ref: ingress-nginx
    release_namespace: ingress-nginx
    create_namespace: true
    kubeconfig: /etc/rancher/k3s/k3s.yaml
